<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
    <div class="test" style="height: 140px ; display: flex; align-items: center">
        <div style="width: 290px; height: 80px; text-align: center" >
            <a href="https://asean.org/">
                <img src="https://asean-sme-academy.org/media/wysiwyg/asean_emblem_2_.png"  style="height: 80px; width: 156.89px">
            </a>
        </div>
        <div style="width: 290px; height: 80px; text-align: center" >
            <a href="https://asean.org/">
                <img src="https://asean-sme-academy.org/static/version1658457290/frontend/Asean/default/en_US/images/us-asean-bc.png" style="height: 80px; width: 95.73px">
            </a>
        </div>
        <div style="width: 290px; height: 80px; text-align: center" >
            <a href="https://asean.org/">
                <img src="https://asean-sme-academy.org/media/wysiwyg/MicrosoftTeams-image_3_.png"  style="height: 80px; width: 80.52px">
            </a>
        </div>
        <div style="width: 290px; height: 80px; text-align: center" >
            <a href="https://asean.org/">
                <img src="https://asean-sme-academy.org/media/catalog/category/PTTC_logo.png" style="height: 80px; width: 218.78px">
            </a>
        </div>
        <div style="width: 290px; height: 80px; text-align: center" >
            <a href="https://asean.org/">
                <img src="https://asean-sme-academy.org/static/version1658457290/frontend/Asean/default/en_US/images/usaid-logo.svg"  style="height: 80px; width: 268px">
            </a>
        </div>
    </div>





<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "Magento_Customer/js/block-submit-on-send": {-->
<!--                "formId": "contact-form"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->

<div style="height: 400px; width: 1240px; display: flex; align-items: center; background: #0a3d91; ">
    <div style="width: 413px; height: 285px; padding-left: 20px">
        <a href="">
            <img src="https://asean-sme-academy.org/static/version1658457290/frontend/Asean/default/en_US/images/logo.svg" style="width: 215.83px; height: 50px">
        </a>
        <div style="line-height: 30px; font-family: 'Rubik',sans-serif; font-size: 16px; margin-top: 15px">
            <div style="width: 340px; color: white">
                <p>Training and Resources for Small and Medium Enterprises in ASEAN.</p>
            </div>
            <div style="display: flex; width: 340px;">
                <a href="/contact-us" style="color: white">Contact Us</a>
                <a tabindex="0" href="#" style="color: white; padding-left: 10px">About Us</a>
            </div>
            <div>

            </div>
        </div>
    </div>
    <div style="width: 206px; height: 285px; padding-top: 50px";>
        <div style="font-family: 'Rubik',sans-serif; font-size: 1.6rem; color: white">
            <p><b>Course</b></p>
        </div>
        <div style="padding-top: 10px">
            <ul style="list-style: none;">
                <li>
                    <a href="#" style="color: white">Finance & Accounting</a>
                </li>
                <li>
                    <a href="#" style="color: white">Management</a>
                </li>
                <li>
                    <a href="#" style="color: white">Technology</a>
                </li>
                <li>
                    <a href="#" style="color: white">Operations</a>
                </li>
                <li>
                    <a href="#" style="color: white">Trade & Logistics</a>
                </li>
                <li>
                    <a href="#" style="color: white">Marketing</a>
                </li>
            </ul>
        </div>
    </div>
    <div style="width: 207px; height: 285px";></div>
    <div style="width: 413px; height: 285px; padding-top: 50px">
        <div>
            <div style="font-family: 'Rubik',sans-serif; font-size: 1.6rem; color: white">
                <p><b>SUBSCRIBE TO OUR NEWSLETTER</b></p>
                <div style="padding-top: 10px">
                    <p>Sign up for our newsletter to get the latest news, announcements and special offers</p>
                </div>
            </div>
        </div>
        <br>
        <div>
            <form>
                <input type="email" placeholder="Email Address" style="width: 200px">
                <button type="submit" style="background: red; color: white; border-radius: 20px;"><b>SUBSCRIBE</b></button>
            </form>
        </div>
    </div>
</div>
<div style="height: 100px; width: 1240px; display: flex; align-items: center; background: #0a3d91; ">
    <small>
        <span style="padding-left:30px; font-family: 'Rubik',sans-serif; font-size: 16px; color: white">© 2022 ASEAN SME Academy</span>
    </small>
    <div style="font-family: 'Rubik',sans-serif; font-size: 16px; padding-left: 700px">
        <a href="#" style="color: white">Privacy Policy</a>
        <a href="#" style="color: white; padding-left: 10px">Terms of Use</a>
    </div>
</div>



