<!--font-->
<div>
    <h1>H1 RUBIK BOLD 48px/48px</h1>

    <h2>H2 RUBIK BOLD 30PX/36PX</h2>

    <h3>H3 RUBIK BOLD 24PX/30PX</h3>

    <h4>H4 RUBIK BOLD 18PX/24PX</h4>

    <h5>H5 Rubik Bold 16px/24px</h5>

    <h6>H6 RUBIK BOLD 12PX/30PX</h6>

    <p>
        H5 Rubik Regular 16px/24px
        At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
        dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
        gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet
    </p>

    <a class="testlink" href="#"">Default – Rubik Regular 16px/24px</a>

    <div style="margin-top: 30px">
        <ul>
            <li>100% Cotton Moleskin</li>
            <li>Mid Weight</li>
            <li>Soft Brushed Finish</li>
            <li>Full Button</li>
            <li>Double Pocket</li>
        </ul>

        <ol>
            <li>100% Cotton Moleskin</li>
            <li>Mid Weight</li>
            <li>Soft Brushed Finish</li>
            <li>Full Button</li>
            <li>Double Pocket</li>
        </ol>
    </div>
</div>
<hr>

<!--button-->
<div style="margin-top: 3%">
    Primary Button & Secondary Button
    <br>
    <button type="submit" class="action primary test">abc</button>
    <button type="submit" class="action secondary test">abc</button>
    <button type="submit" class="test disabled" disabled>abc</button>
    <div class="a" style="background: #173E8C; height: 100px; margin-top: 30px">
        <button type="submit" class="action secondary2 test" style="margin-top: 30px">abc</button>
        <button type="submit" class="test disabled2" style="margin-top: 30px" disabled><span class="bn">abc</span></button>
    </div>
    <hr>
    Close Button
    <div style="background: #0A3D91FF; height: 40px;">
        <button class="xyz" style="display: flex; align-items: center;">
            <span class="cancel_2"></span>
            <b>UNREGISTER</b>
        </button>
    </div>
    <button class="xy" style="display: flex; align-items: center;">
        <span class="cancel_1"></span>
        <b>REMOVE FROM WISHLIST</b>
    </button>
    <hr>
    Social Buttons
    <div class="a" style="background: #173E8C; height: 100px;">
        <div style="padding-top: 30px; display: flex">
            <button class="abc" style="display: flex; align-items: center;">
                <a class="facebook1" href="#"></a>
                <b style="padding-left: 5px">VISIT FACEBOOK GROUP</b>
            </button>
            <button class="ab" style="display: flex; align-items: center;">
                <a class="whatsapp" href="#"></a>
                <b style="padding-left: 5px">VISIT WHATSAPP GROUP</b>
            </button>
            <br>
            <button class="fb" style="display: flex; align-items: center;">
                <a class="iconfb" href="#"></a>
                <b style="padding-left: 5px">FACEBOOK</b>
            </button>
            <button class="gg" style="display: flex; align-items: center;">
                <a class="icongg" href="#"></a>
                <b style="padding-left: 5px">GOOGLE</b>
            </button>
            <button class="tt" style="display: flex; align-items: center;">
                <a class="icontt" href="#"></a>
                <b style="padding-left: 5px">TWITTER</b>
            </button>
        </div>
    </div>
</div>
<hr>

<!--form element-->
<div>
    Label
    <br>
    <label>RUBIK BOLD 12PX/24PX</label>
    <hr>
    Fields
    <br>
    <div>
        <input type="text" placeholder="Text" style="height: 44px; width: 450px">
        <input type="text" placeholder="Text" style="height: 44px; width: 450px" disabled>
    </div>

    <div style="margin-top: 20px">
        <input type="text" placeholder="text" class="input-text valid" style="height: 44px; width: 450px">
        <input type="text" placeholder="text" class="input-text mage-error" style="height: 44px; width: 450px">
    </div>
    <hr>
    Text Area
    <br>
    <textarea style="height: 180px; width: 450px" placeholder="Test"></textarea>
    <textarea style="height: 180px; width: 450px" placeholder="Test" disabled></textarea>
    <hr>
    Drop Down Lists
    <div>
        <select class="select color">
            <option value="1">Green</option>
            <option value="2" selected="selected">Black</option>
            <option value="3">White</option>
            <option value="4">Pink</option>
            <option value="5">Red</option>
        </select>

        <select class="select color" disabled>
            <option value="1">Green</option>
            <option value="2" selected="selected">Black</option>
            <option value="3">White</option>
            <option value="4">Pink</option>
            <option value="5">Red</option>
        </select>
    </div>
    <hr>
    Radio Buttons
    <div>
        <input type="radio" class="radio1" name="a" value="1" checked="">
        <input type="radio" class="radio1" name="a" value="2">
        <input type="radio" class="radio1" name="b" value="1" checked="" disabled>
    </div>
    <hr>
    Checkboxes
    <div>
        <input type="checkbox" checked="x">
        <input type="checkbox" style="margin-left: 20px">
        <input type="checkbox" style="margin-left: 20px" disabled>
    </div>
</div>


<!--alert-->
<div style="margin-top: 3%">
    <hr>
    Status & Labels
    <div class="a" style="background: #173E8C; height: 50px; display: flex; align-items: center;">
        <div class="sl in_progress">
            <span>IN PROGRESS</span>
        </div>
        <div class="sl upcoming">
            <span>UPCOMING</span>
        </div>
        <div class="sl past">
            <span>PAST</span>
        </div>
        <div class="sl completed">
            <span>COMPLETED</span>
        </div>
        <div class="sl registered">
            <span class="registered">REGISTERED</span>
        </div>
        <div class="sl certificate">
            <span class="certificate">CERTIFICATE</span>
        </div>
        <div class="sl category">
            <span>CATEGORY</span>
        </div>
    </div>
    <hr>
    Alerts
    <div>
        <div class="message-success success message">
            THIS IS SUCCESS MESSAGE
        </div>
        <div class="message-error error message">
            THIS IS AN ERROR MESSAGE
        </div>
        <div class="message-warning warning message">
            THIS IS A WARNING MESSAGE
        </div>
    </div>
</div>
<hr>

<!--icon-->
<div style="margin-top: 3%">
    Primary Icons
    <br>
    <span class="account"></span>
    <span class="bookmark"></span>
    <span class="search"></span>
    <span class="menu"></span>
    <hr>
    Material Icons
    <br>
    <span class="hourglass"></span>
    <span class="bookmark2"></span>
    <span class="help"></span>
    <span class="check"></span>
    <span class="check_circle"></span>
    <span class="keyboard_arrow_right"></span>
    <span class="arrow_drop_down"></span>
    <span class="arrow_drop_up"></span>
    <span class="error"></span>
    <span class="cancel_1"></span>
    <div style="background: #0A3D91FF; height: 30px; padding-top: 10px">
        <span class="cancel_2"></span>
    </div>
    <hr>
    Custom Icons
    <br>
    <a class="stitch" href="#"></a>
    <hr>
    Social Icons
    <br>
    <div class="social">
        <a class="facebook" href="#"></a>
        <a class="twitter" href="#"></a>
        <a class="linkedIn" href="#"></a>
    </div>
    <hr>
    Flag
    <br>
    <div class="flag">
        <a class="us" href="#"></a>
        <a class="mc" href="#"></a>
        <a class="th" href="#"></a>
        <a class="vn" href="#"></a>
    </div>
</div>

